{
    'name': 'Quản lý Nhân sự',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Module quản lý nhân sự, bảo hiểm, bằng cấp (Cấu trúc phân tách file)',
    'depends': ['base', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/chuc_vu.xml',
        'views/danh_sach_chung_chi_bang_cap.xml',
        'views/chung_chi_bang_cap.xml',
        'views/don_vi.xml',
        'views/lich_su_cong_tac.xml',
        'views/nhan_vien.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}